name: CI

on:
  push:
    tags:
      - alpine-*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and test Alpine Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: ./alpine/Dockerfile
          context: ./alpine
          target: test

      - name: Compute image tags
        id: tags
        run: echo ::set-output name=TAGS::xfournet/jready:${GITHUB_REF#refs/tags/},xfournet/jready:alpine

      - name: Build and publish Alpine Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: ./alpine/Dockerfile
          context: ./alpine
          tags: ${{ steps.tags.outputs.TAGS }}
