name: Test image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: xfournet
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and test Alpine Docker image
        id: alpine_build
        uses: docker/build-push-action@v2.7.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: ./alpine/Dockerfile
          context: ./alpine
          target: test

      - name: Build and test Busybox Docker image
        id: busybox_build
        uses: docker/build-push-action@v2.7.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: ./busybox/Dockerfile
          context: ./busybox
          target: test
